export interface Player {
  id: number; // 선수의 고유 ID
  realname: string; // 선수 이름
  nickname: string; // 게임 내 닉네임
  date_of_birth: string; // 생년월일 (YYYY-MM-DD 형식)
  nationality: string; // 국적
  debut_date: string; // 데뷔 날짜
  position: "top" | "jungle" | "mid" | "ADCarry" | "support"; // 포지션
  team_id: number; // 소속 팀 ID
  agency: string; // 소속사
  gamename: string; //롤 아이디
  social?: {
    insta?: string;
    youtube?: string;
    facebook?: string;
    X?: string;
    soop?: string;
    chzzk?: string;
  }; // SNS 링크
  fanVotes?: number; // 팬 투표 수
  profile_image_url: string; //선수 프로필 이미지
  backgroundImageUrl?: string; //선수 상단 배경 이미지
}

export type PlayerCardData = Pick<
  Player,
  "id" | "realname" | "nickname" | "position" | "social" | "profile_image_url"
>;

// // types/player.ts
// export const samplePlayers: Player[] = [
//   {
//     id: 1,
//     realname: "이상혁",
//     nickname: "Faker",
//     date_of_birth: "1996-05-07",
//     nationality: "대한민국",
//     debut_date: "2013-04-06",
//     position: "MID",
//     team_id: 101,
//     agency: "FANABLE",
//     gamename: "Hide on bush#KR1",
//     social: {
//       insta: "https://instagram.com/faker",
//       X: "https://x.com/faker",
//       youtube: "https://youtube.com/faker",
//       soop: "https://soop.tv/faker",
//     },
//     fanVotes: 5000,
//     profileImageUrl: "/images/profile/Faker.png",
//     backgroundImageUrl: "/images/background/Faker.png",
//   },
//   {
//     id: 2,
//     realname: "류민석",
//     nickname: "Keria",
//     date_of_birth: "2002-10-14",
//     nationality: "대한민국",
//     debut_date: "2019-10-12",
//     position: "SUPPORT",
//     team_id: 101,
//     agency: "FANABLE",
//     gamename: "Keria#KR1",
//     social: {
//       insta: "https://instagram.com/keria",
//       X: "https://x.com/keria",
//       youtube: "https://youtube.com/keria",
//       soop: "https://soop.tv/keria",
//     },
//     fanVotes: 4500,
//     profileImageUrl: "/images/profile/Keria.png",
//   },
//   {
//     id: 3,
//     realname: "이민형",
//     nickname: "Gumayusi",
//     date_of_birth: "2002-02-06",
//     nationality: "대한민국",
//     debut_date: "2019-11-25",
//     position: "BOT",
//     team_id: 101,
//     agency: "FANABLE",
//     gamename: "Gumayusi#KR1",
//     social: {
//       insta: "https://instagram.com/gumayusi",
//       X: "https://x.com/gumayusi",
//       youtube: "https://youtube.com/gumayusi",
//       soop: "https://soop.tv/gumayusi",
//     },
//     fanVotes: 4700,
//     profileImageUrl: "/images/profile/Gumayusi.png",
//   },
//   {
//     id: 4,
//     realname: "최우제",
//     nickname: "Zeus",
//     date_of_birth: "2004-01-31",
//     nationality: "대한민국",
//     debut_date: "2021-01-21",
//     position: "TOP",
//     team_id: 101,
//     agency: "T1",
//     gamename: "Zeus#KR1",
//     fanVotes: 4800,
//     profileImageUrl: "/images/profile/Zeus.png",
//   },
//   {
//     id: 5,
//     realname: "장하권",
//     nickname: "Nuguri",
//     date_of_birth: "2000-07-03",
//     nationality: "대한민국",
//     debut_date: "2017-12-27",
//     position: "TOP",
//     team_id: 102,
//     agency: "DWG KIA",
//     gamename: "Nuguri#KR1",
//     fanVotes: 4600,
//     profileImageUrl: "/images/profile/Nuguri.png",
//   },
//   {
//     id: 6,
//     realname: "문우찬",
//     nickname: "Canyon",
//     date_of_birth: "2001-06-18",
//     nationality: "대한민국",
//     debut_date: "2019-01-16",
//     position: "JUNGLE",
//     team_id: 102,
//     agency: "DWG KIA",
//     gamename: "Canyon#KR1",
//     fanVotes: 4900,
//     profileImageUrl: "/images/profile/Canyon.png",
//   },
//   {
//     id: 7,
//     realname: "한왕호",
//     nickname: "Peanut",
//     date_of_birth: "1998-02-03",
//     nationality: "대한민국",
//     debut_date: "2015-11-23",
//     position: "JUNGLE",
//     team_id: 103,
//     agency: "Gen.G",
//     gamename: "Peanut#KR1",
//     fanVotes: 4700,
//     profileImageUrl: "/images/profile/Peanut.png",
//   },
//   {
//     id: 8,
//     realname: "정지훈",
//     nickname: "Chovy",
//     date_of_birth: "2001-03-03",
//     nationality: "대한민국",
//     debut_date: "2018-11-25",
//     position: "MID",
//     team_id: 103,
//     agency: "Gen.G",
//     gamename: "Chovy#KR1",
//     fanVotes: 4800,
//     profileImageUrl: "/images/profile/Chovy.png",
//   },
//   {
//     id: 9,
//     realname: "김하람",
//     nickname: "Deft",
//     date_of_birth: "1996-10-23",
//     nationality: "대한민국",
//     debut_date: "2013-05-07",
//     position: "BOT",
//     team_id: 104,
//     agency: "DRX",
//     gamename: "Deft#KR1",
//     fanVotes: 4850,
//     profileImageUrl: "/images/profile/Deft.png",
//   },
//   {
//     id: 10,
//     realname: "박재혁",
//     nickname: "Ruler",
//     date_of_birth: "1999-07-17",
//     nationality: "대한민국",
//     debut_date: "2016-05-09",
//     position: "BOT",
//     team_id: 103,
//     agency: "Gen.G",
//     gamename: "Ruler#KR1",
//     fanVotes: 4750,
//     profileImageUrl: "/images/profile/Ruler.png",
//   },
//   {
//     id: 11,
//     realname: "손시우",
//     nickname: "Lehends",
//     date_of_birth: "1999-01-24",
//     nationality: "대한민국",
//     debut_date: "2017-12-27",
//     position: "SUPPORT",
//     team_id: 105,
//     agency: "KT Rolster",
//     gamename: "Lehends#KR1",
//     fanVotes: 4400,
//     profileImageUrl: "/images/profile/Lehends.png",
//   },
//   // Additional TOP laners
//   {
//     id: 12,
//     realname: "김창동",
//     nickname: "Canna",
//     date_of_birth: "2000-03-23",
//     nationality: "대한민국",
//     debut_date: "2020-01-15",
//     position: "TOP",
//     team_id: 105,
//     agency: "DRX",
//     gamename: "Canna#KR1",
//     fanVotes: 4300,
//     profileImageUrl: "/images/profile/Canna.png",
//   },
//   {
//     id: 13,
//     realname: "김기인",
//     nickname: "Kiin",
//     date_of_birth: "1999-05-28",
//     nationality: "대한민국",
//     debut_date: "2017-12-27",
//     position: "TOP",
//     team_id: 106,
//     agency: "KT Rolster",
//     gamename: "Kiin#KR1",
//     fanVotes: 4400,
//     profileImageUrl: "/images/profile/Kiin.png",
//   },
//   {
//     id: 14,
//     realname: "박종범",
//     nickname: "Morgan",
//     date_of_birth: "2000-03-03",
//     nationality: "대한민국",
//     debut_date: "2020-05-15",
//     position: "TOP",
//     team_id: 107,
//     agency: "Fredit BRION",
//     gamename: "Morgan#KR1",
//     fanVotes: 4200,
//     profileImageUrl: "/images/profile/Morgan.png",
//   },

//   // Additional JUNGLE
//   {
//     id: 15,
//     realname: "서창동",
//     nickname: "Umti",
//     date_of_birth: "1999-08-12",
//     nationality: "대한민국",
//     debut_date: "2018-01-16",
//     position: "JUNGLE",
//     team_id: 108,
//     agency: "Kwangdong Freecs",
//     gamename: "Umti#KR1",
//     fanVotes: 4100,
//     profileImageUrl: "/images/profile/Umti.png",
//   },
//   {
//     id: 16,
//     realname: "김태민",
//     nickname: "Clid",
//     date_of_birth: "1999-10-19",
//     nationality: "대한민국",
//     debut_date: "2017-05-15",
//     position: "JUNGLE",
//     team_id: 109,
//     agency: "Gen.G",
//     gamename: "Clid#KR1",
//     fanVotes: 4300,
//     profileImageUrl: "/images/profile/Clid.png",
//   },
//   {
//     id: 17,
//     realname: "문현준",
//     nickname: "Pyosik",
//     date_of_birth: "2000-05-12",
//     nationality: "대한민국",
//     debut_date: "2019-12-24",
//     position: "JUNGLE",
//     team_id: 110,
//     agency: "DRX",
//     gamename: "Pyosik#KR1",
//     fanVotes: 4200,
//     profileImageUrl: "/images/profile/Pyosik.png",
//   },

//   // Additional MID
//   {
//     id: 18,
//     realname: "곽보성",
//     nickname: "Bdd",
//     date_of_birth: "1999-03-01",
//     nationality: "대한민국",
//     debut_date: "2016-05-15",
//     position: "MID",
//     team_id: 111,
//     agency: "Gen.G",
//     gamename: "Bdd#KR1",
//     fanVotes: 4400,
//     profileImageUrl: "/images/profile/Bdd.png",
//   },
//   {
//     id: 19,
//     realname: "이예찬",
//     nickname: "Scout",
//     date_of_birth: "1998-07-15",
//     nationality: "대한민국",
//     debut_date: "2016-03-15",
//     position: "MID",
//     team_id: 112,
//     agency: "EDG",
//     gamename: "Scout#KR1",
//     fanVotes: 4300,
//     profileImageUrl: "/images/profile/Scout.png",
//   },
//   {
//     id: 20,
//     realname: "허수",
//     nickname: "ShowMaker",
//     date_of_birth: "2000-07-22",
//     nationality: "대한민국",
//     debut_date: "2019-01-16",
//     position: "MID",
//     team_id: 113,
//     agency: "DWG KIA",
//     gamename: "ShowMaker#KR1",
//     fanVotes: 4600,
//     profileImageUrl: "/images/profile/ShowMaker.png",
//   },

//   // Additional BOT
//   {
//     id: 21,
//     realname: "김동현",
//     nickname: "Aiming",
//     date_of_birth: "2000-07-20",
//     nationality: "대한민국",
//     debut_date: "2018-01-16",
//     position: "BOT",
//     team_id: 114,
//     agency: "KT Rolster",
//     gamename: "Aiming#KR1",
//     fanVotes: 4300,
//     profileImageUrl: "/images/profile/Aiming.png",
//   },
//   {
//     id: 22,
//     realname: "박진성",
//     nickname: "Teddy",
//     date_of_birth: "1998-03-15",
//     nationality: "대한민국",
//     debut_date: "2017-05-15",
//     position: "BOT",
//     team_id: 115,
//     agency: "T1",
//     gamename: "Teddy#KR1",
//     fanVotes: 4400,
//     profileImageUrl: "/images/profile/Teddy.png",
//   },

//   // Additional SUPPORT
//   {
//     id: 23,
//     realname: "조용인",
//     nickname: "Kellin",
//     date_of_birth: "2000-09-23",
//     nationality: "대한민국",
//     debut_date: "2019-12-24",
//     position: "SUPPORT",
//     team_id: 116,
//     agency: "DRX",
//     gamename: "Kellin#KR1",
//     fanVotes: 4100,
//     profileImageUrl: "/images/profile/Kellin.png",
//   },
//   {
//     id: 24,
//     realname: "김혁규",
//     nickname: "Delight",
//     date_of_birth: "2001-05-15",
//     nationality: "대한민국",
//     debut_date: "2020-05-15",
//     position: "SUPPORT",
//     team_id: 117,
//     agency: "KT Rolster",
//     gamename: "Delight#KR1",
//     fanVotes: 4000,
//     profileImageUrl: "/images/profile/Delight.png",
//   },
//   {
//     id: 25,
//     realname: "이상혁",
//     nickname: "Effort",
//     date_of_birth: "2000-03-23",
//     nationality: "대한민국",
//     debut_date: "2017-12-27",
//     position: "SUPPORT",
//     team_id: 118,
//     agency: "Liiv SANDBOX",
//     gamename: "Effort#KR1",
//     fanVotes: 4200,
//     profileImageUrl: "/images/profile/Effort.png",
//   },
// ];
