export interface Player {
    id: number; // 선수의 고유 ID
    realname: string; // 선수 이름
    nickname: string; // 게임 내 닉네임
    date_of_birth: string; // 생년월일 (YYYY-MM-DD 형식)
    nationality: string; // 국적
    debut_date: string; // 데뷔 날짜
    position: "TOP" | "JUNGLE" | "MID" | "BOT" | "SUPPORT"; // 포지션
    team_id: number; // 소속 팀 ID
    agency: string; // 소속사
    gamename: string; //롤 아이디
    social?: {
      insta?: string;
      youtube?: string;
      facebook?: string;
      X?: string;
      soop?: string;
      chzzk?: string;
    }; // SNS 링크
    fanVotes?: number; // 팬 투표 수
    profileImageUrl: string; //선수 프로필 이미지
    backgroundImageUrl?: string; //선수 상단 배경 이미지
  }


export type PlayerCardData = Pick<Player, "id" | "realname" | "nickname" | "position" | "social" | "profileImageUrl">;

// types/player.ts
export const samplePlayers: Player[] = [
    {
      id: 1,
      realname: "이상혁",
      nickname: "Faker",
      date_of_birth: "1996-05-07",
      nationality: "대한민국",
      debut_date: "2013-04-06",
      position: "MID",
      team_id: 101,
      agency: "FANABLE",
      gamename: "Hide on bush#KR1",
      social: {
        insta: "https://instagram.com/faker",
        X: "https://x.com/faker",
        youtube: "https://youtube.com/faker",
        soop: "https://soop.tv/faker",
      },
      fanVotes: 5000,
      profileImageUrl: "/images/profile/Faker.png",
      backgroundImageUrl: "/images/background/Faker.png",
    },
    {
      id: 2,
      realname: "류민석",
      nickname: "Keria",
      date_of_birth: "2002-10-14",
      nationality: "대한민국",
      debut_date: "2019-10-12",
      position: "SUPPORT",
      team_id: 101,
      agency: "FANABLE",
      gamename: "Keria#KR1",
      social: {
        insta: "https://instagram.com/keria",
        X: "https://x.com/keria",
        youtube: "https://youtube.com/keria",
        soop: "https://soop.tv/keria",
      },
      fanVotes: 4500,
      profileImageUrl: "/images/profile/Keria.png",
    },
    {
      id: 3,
      realname: "이민형",
      nickname: "Gumayusi",
      date_of_birth: "2002-02-06",
      nationality: "대한민국",
      debut_date: "2019-11-25",
      position: "BOT",
      team_id: 101,
      agency: "FANABLE",
      gamename: "Gumayusi#KR1",
      social: {
        insta: "https://instagram.com/gumayusi",
        X: "https://x.com/gumayusi",
        youtube: "https://youtube.com/gumayusi",
        soop: "https://soop.tv/gumayusi",
      },
      fanVotes: 4700,
      profileImageUrl: "/images/profile/Gumayusi.png",
    },
    fanVotes: 4700,
    profileImageUrl: "/images/profile/Gumayusi.png",
  },
  {
    id: 4,
    name: "최우제",
    nickname: "Zeus",
    birthdate: "2004-01-31",
    nationality: "대한민국",
    debutDate: "2021-01-21",
    position: "TOP",
    teamId: 101,
    agency: "T1",
    gamename: "Zeus#KR1",
    fanVotes: 4800,
    profileImageUrl: "/images/profile/Zeus.png",
  },
  {
    id: 5,
    name: "장하권",
    nickname: "Nuguri",
    birthdate: "2000-07-03",
    nationality: "대한민국",
    debutDate: "2017-12-27",
    position: "TOP",
    teamId: 102,
    agency: "DWG KIA",
    gamename: "Nuguri#KR1",
    fanVotes: 4600,
    profileImageUrl: "/images/profile/Nuguri.png",
  },
  {
    id: 6,
    name: "문우찬",
    nickname: "Canyon",
    birthdate: "2001-06-18",
    nationality: "대한민국",
    debutDate: "2019-01-16",
    position: "JUNGLE",
    teamId: 102,
    agency: "DWG KIA",
    gamename: "Canyon#KR1",
    fanVotes: 4900,
    profileImageUrl: "/images/profile/Canyon.png",
  },
  {
    id: 7,
    name: "한왕호",
    nickname: "Peanut",
    birthdate: "1998-02-03",
    nationality: "대한민국",
    debutDate: "2015-11-23",
    position: "JUNGLE",
    teamId: 103,
    agency: "Gen.G",
    gamename: "Peanut#KR1",
    fanVotes: 4700,
    profileImageUrl: "/images/profile/Peanut.png",
  },
  {
    id: 8,
    name: "정지훈",
    nickname: "Chovy",
    birthdate: "2001-03-03",
    nationality: "대한민국",
    debutDate: "2018-11-25",
    position: "MID",
    teamId: 103,
    agency: "Gen.G",
    gamename: "Chovy#KR1",
    fanVotes: 4800,
    profileImageUrl: "/images/profile/Chovy.png",
  },
  {
    id: 9,
    name: "김하람",
    nickname: "Deft",
    birthdate: "1996-10-23",
    nationality: "대한민국",
    debutDate: "2013-05-07",
    position: "BOT",
    teamId: 104,
    agency: "DRX",
    gamename: "Deft#KR1",
    fanVotes: 4850,
    profileImageUrl: "/images/profile/Deft.png",
  },
  {
    id: 10,
    name: "박재혁",
    nickname: "Ruler",
    birthdate: "1999-07-17",
    nationality: "대한민국",
    debutDate: "2016-05-09",
    position: "BOT",
    teamId: 103,
    agency: "Gen.G",
    gamename: "Ruler#KR1",
    fanVotes: 4750,
    profileImageUrl: "/images/profile/Ruler.png",
  },
  {
    id: 11,
    name: "손시우",
    nickname: "Lehends",
    birthdate: "1999-01-24",
    nationality: "대한민국",
    debutDate: "2017-12-27",
    position: "SUPPORT",
    teamId: 105,
    agency: "KT Rolster",
    gamename: "Lehends#KR1",
    fanVotes: 4400,
    profileImageUrl: "/images/profile/Lehends.png",
  },
  // Additional TOP laners
  {
    id: 12,
    name: "김창동",
    nickname: "Canna",
    birthdate: "2000-03-23",
    nationality: "대한민국",
    debutDate: "2020-01-15",
    position: "TOP",
    teamId: 105,
    agency: "DRX",
    gamename: "Canna#KR1",
    fanVotes: 4300,
    profileImageUrl: "/images/profile/Canna.png",
  },
  {
    id: 13,
    name: "김기인",
    nickname: "Kiin",
    birthdate: "1999-05-28",
    nationality: "대한민국",
    debutDate: "2017-12-27",
    position: "TOP",
    teamId: 106,
    agency: "KT Rolster",
    gamename: "Kiin#KR1",
    fanVotes: 4400,
    profileImageUrl: "/images/profile/Kiin.png",
  },
  {
    id: 14,
    name: "박종범",
    nickname: "Morgan",
    birthdate: "2000-03-03",
    nationality: "대한민국",
    debutDate: "2020-05-15",
    position: "TOP",
    teamId: 107,
    agency: "Fredit BRION",
    gamename: "Morgan#KR1",
    fanVotes: 4200,
    profileImageUrl: "/images/profile/Morgan.png",
  },

  // Additional JUNGLE
  {
    id: 15,
    name: "서창동",
    nickname: "Umti",
    birthdate: "1999-08-12",
    nationality: "대한민국",
    debutDate: "2018-01-16",
    position: "JUNGLE",
    teamId: 108,
    agency: "Kwangdong Freecs",
    gamename: "Umti#KR1",
    fanVotes: 4100,
    profileImageUrl: "/images/profile/Umti.png",
  },
  {
    id: 16,
    name: "김태민",
    nickname: "Clid",
    birthdate: "1999-10-19",
    nationality: "대한민국",
    debutDate: "2017-05-15",
    position: "JUNGLE",
    teamId: 109,
    agency: "Gen.G",
    gamename: "Clid#KR1",
    fanVotes: 4300,
    profileImageUrl: "/images/profile/Clid.png",
  },
  {
    id: 17,
    name: "문현준",
    nickname: "Pyosik",
    birthdate: "2000-05-12",
    nationality: "대한민국",
    debutDate: "2019-12-24",
    position: "JUNGLE",
    teamId: 110,
    agency: "DRX",
    gamename: "Pyosik#KR1",
    fanVotes: 4200,
    profileImageUrl: "/images/profile/Pyosik.png",
  },

  // Additional MID
  {
    id: 18,
    name: "곽보성",
    nickname: "Bdd",
    birthdate: "1999-03-01",
    nationality: "대한민국",
    debutDate: "2016-05-15",
    position: "MID",
    teamId: 111,
    agency: "Gen.G",
    gamename: "Bdd#KR1",
    fanVotes: 4400,
    profileImageUrl: "/images/profile/Bdd.png",
  },
  {
    id: 19,
    name: "이예찬",
    nickname: "Scout",
    birthdate: "1998-07-15",
    nationality: "대한민국",
    debutDate: "2016-03-15",
    position: "MID",
    teamId: 112,
    agency: "EDG",
    gamename: "Scout#KR1",
    fanVotes: 4300,
    profileImageUrl: "/images/profile/Scout.png",
  },
  {
    id: 20,
    name: "허수",
    nickname: "ShowMaker",
    birthdate: "2000-07-22",
    nationality: "대한민국",
    debutDate: "2019-01-16",
    position: "MID",
    teamId: 113,
    agency: "DWG KIA",
    gamename: "ShowMaker#KR1",
    fanVotes: 4600,
    profileImageUrl: "/images/profile/ShowMaker.png",
  },

  // Additional BOT
  {
    id: 21,
    name: "김동현",
    nickname: "Aiming",
    birthdate: "2000-07-20",
    nationality: "대한민국",
    debutDate: "2018-01-16",
    position: "BOT",
    teamId: 114,
    agency: "KT Rolster",
    gamename: "Aiming#KR1",
    fanVotes: 4300,
    profileImageUrl: "/images/profile/Aiming.png",
  },
  {
    id: 22,
    name: "박진성",
    nickname: "Teddy",
    birthdate: "1998-03-15",
    nationality: "대한민국",
    debutDate: "2017-05-15",
    position: "BOT",
    teamId: 115,
    agency: "T1",
    gamename: "Teddy#KR1",
    fanVotes: 4400,
    profileImageUrl: "/images/profile/Teddy.png",
  },

  // Additional SUPPORT
  {
    id: 23,
    name: "조용인",
    nickname: "Kellin",
    birthdate: "2000-09-23",
    nationality: "대한민국",
    debutDate: "2019-12-24",
    position: "SUPPORT",
    teamId: 116,
    agency: "DRX",
    gamename: "Kellin#KR1",
    fanVotes: 4100,
    profileImageUrl: "/images/profile/Kellin.png",
  },
  {
    id: 24,
    name: "김혁규",
    nickname: "Delight",
    birthdate: "2001-05-15",
    nationality: "대한민국",
    debutDate: "2020-05-15",
    position: "SUPPORT",
    teamId: 117,
    agency: "KT Rolster",
    gamename: "Delight#KR1",
    fanVotes: 4000,
    profileImageUrl: "/images/profile/Delight.png",
  },
  {
    id: 25,
    name: "이상혁",
    nickname: "Effort",
    birthdate: "2000-03-23",
    nationality: "대한민국",
    debutDate: "2017-12-27",
    position: "SUPPORT",
    teamId: 118,
    agency: "Liiv SANDBOX",
    gamename: "Effort#KR1",
    fanVotes: 4200,
    profileImageUrl: "/images/profile/Effort.png",
  },
];
